export const USER_AUTH_SUCCESS = 'USER_AUTH_SUCCESS';
export const USER_AUTH_FAILED = 'USER_AUTH_FAILED';
export const USER_AUTH_LOADING = 'USER_AUTH_LOADING';
export const USER_AUTH_LOGOUT = 'USER_AUTH_LOGOUT';
